// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqbchlyqpzpelfcwkigs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxYmNobHlxcHpwZWxmY3draWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzgxMzAsImV4cCI6MjA3MTQ1NDEzMH0.-jQB8jNzwrH_7cMcIISHxti4vbOqhJpm8wbCLg3FuNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});